---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1wqf57rp54557ph7yu7tzgzmtggqmm0z9pkr4822u7gmcat3z5a4qgxfwpy"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1wqf57rp54557ph7yu7tzgzmtggqmm0z9pkr4822u7gmcat3z5a4qgxfwpy"
